/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List catalog products visible to the realm */
        get: operations["listCatalogProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List catalog prices for product(s)
         * @description Default sort: display_priority ASC, unit_amount ASC, catalog_price_id ASC.
         */
        get: operations["listCatalogPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Checkout Session
         * @description Creates a hosted checkout session. You may reference items by `catalog_price_id` (preferred) or by provider `price_id`.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Portal Session */
        post: operations["createPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices (Realm + Account scoped) */
        get: operations["listInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single invoice */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions (Realm + Account scoped) */
        get: operations["listSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single subscription */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payments (Realm + Account scoped) */
        get: operations["listPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single payment */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a billing event (fact only)
         * @description Accepts one event and writes it synchronously. Events are fact records only (e.g., outcomes) and do not carry pricing/cost semantics.
         *     Idempotency is server-side via the resolved `billing_user_id` and `request_hash`.
         *
         */
        post: operations["recordBillingEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/batch": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a batch of billing events */
        post: operations["recordBillingEventBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get credit balance for the resolved runtime user */
        get: operations["getWalletBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/consume": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically consume xusd (idempotent) */
        post: operations["walletConsume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/adjustments": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a credit change (grant|debit|adjustment, idempotent) */
        post: operations["walletAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        /** List budgets */
        get: operations["listBudgets"];
        put?: never;
        /** Create a budget (xusd-only) */
        post: operations["createBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        /** Get budget */
        get: operations["getBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{budget_id}/close": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a budget and settle remaining usage */
        post: operations["closeBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived platform access token for a principal
         * @description Issues a short-lived platform access token bound to a principal within a realm. This endpoint is intended for service-to-service use; authenticate with `serviceAuth`. The resulting token can be used by frontend clients to call customer-facing Billing APIs on behalf of the same principal.
         */
        post: operations["issuePlatformToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnvelopeBase: {
            /** @example true */
            ok: boolean;
            /** @example OK */
            code: string;
            message?: string;
            meta?: {
                [key: string]: unknown;
            };
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error?: components["schemas"]["Error"];
        };
        CatalogProduct: {
            /** @example 1 */
            catalog_product_id: string;
            /** @example stripe */
            provider: string;
            /** @enum {string} */
            kind: "subscription" | "credit";
            /** @enum {string} */
            status: "active" | "archived" | "draft";
            /**
             * Format: int32
             * @default 100
             */
            display_priority: number;
            /** @example pro_plan */
            name: string;
            /** @example USD */
            default_currency: string;
            presentation_config: components["schemas"]["CatalogProductPresentationConfig"];
            /** @description Default price of the product. Only present when expand=default_price. Null if no price matches filters. */
            default_price?: components["schemas"]["CatalogPrice"] | null;
            feature_families?: components["schemas"]["ProductFeatureFamilies"];
            subscription_state?: components["schemas"]["SubscriptionState"];
        };
        /**
         * @description UI presentation config for customer-facing product surfaces.
         * @default {}
         */
        CatalogProductPresentationConfig: {
            [key: string]: unknown;
        };
        CatalogProductList: components["schemas"]["CatalogProduct"][];
        CatalogPrice: {
            /** @example 10 */
            catalog_price_id: string;
            /** @example 1 */
            catalog_product_id: string;
            /** @example price_123 */
            provider_price_id: string;
            /** @example USD */
            currency: string;
            /**
             * @description Minor units (e.g., cents)
             * @example 2000
             */
            unit_amount: number;
            /** @enum {string|null} */
            recurring_interval?: "month" | "year" | null;
            recurring_count?: number | null;
            display_priority?: number;
            metadata?: components["schemas"]["CatalogPriceMetadata"] | null;
            feature_families?: components["schemas"]["CatalogPriceFeatureFamilies"];
            subscription_state?: components["schemas"]["SubscriptionState"];
        };
        CatalogPriceList: components["schemas"]["CatalogPrice"][];
        CreateCheckoutSessionRequest: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            billing_account_id?: string;
            items: {
                /** @example price_123 */
                price_id?: string;
                /** @example 10 */
                catalog_price_id?: string;
                /** @default 1 */
                quantity: number;
            }[];
            /** Format: uri */
            success_url: string;
            /** Format: uri */
            cancel_url: string;
            display_currency_code?: components["schemas"]["CurrencyCode"];
            settlement_currency_code?: components["schemas"]["CurrencyCode"];
            /** @description Arbitrary key-value pairs (avoid PII). */
            metadata?: Record<string, never>;
        };
        CreateCheckoutSessionResponse: {
            /** Format: uri */
            checkout_url: string;
        };
        CreatePortalSessionRequest: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            billing_account_id?: string;
            /** Format: uri */
            return_url: string;
        };
        CreatePortalSessionResponse: {
            /** Format: uri */
            portal_url: string;
        };
        Invoice: {
            readonly invoice_id?: string;
            readonly billing_account_id?: string;
            /** @enum {string} */
            readonly status?: "draft" | "open" | "paid" | "uncollectible" | "void";
            readonly amount_due?: number;
            readonly amount_paid?: number;
            readonly amount_remaining?: number;
            currency?: components["schemas"]["CurrencyCode"];
            /** Format: uri */
            readonly hosted_invoice_url?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        InvoiceLineItem: {
            /** @enum {string} */
            line_kind?: "recurring" | "usage" | "one_time" | "discount" | "tax" | "other";
            quantity?: number;
            unit_amount?: number;
            total_amount?: number;
            catalog_price_id?: string | null;
            meter_code?: string | null;
            catalog_price?: components["schemas"]["CatalogPrice"];
        };
        InvoiceDetail: components["schemas"]["Invoice"] & {
            invoice_number?: string;
            subtotal?: number;
            tax?: number;
            total?: number;
            /** Format: date-time */
            period_start?: string;
            /** Format: date-time */
            period_end?: string;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            finalized_at?: string | null;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            canceled_at?: string | null;
            line_items?: components["schemas"]["InvoiceLineItem"][];
        };
        InvoiceList: components["schemas"]["Invoice"][];
        Subscription: {
            readonly subscription_id?: string;
            readonly billing_account_id?: string;
            readonly external_subscription_id?: string | null;
            /** @enum {string} */
            readonly status?: "trialing" | "active" | "past_due" | "canceled" | "unpaid";
            display_currency_code?: components["schemas"]["CurrencyCode"];
            settlement_currency_code?: components["schemas"]["CurrencyCode"];
            /** Format: date-time */
            readonly current_period_start?: string;
            /** Format: date-time */
            readonly current_period_end?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            items?: {
                /** @description External provider subscription item id (e.g., Stripe si_...). */
                subscription_item_id?: string;
                price_id?: string;
                quantity?: number;
                readonly catalog_price_id?: string;
                catalog_price?: components["schemas"]["CatalogPrice"];
            }[];
            /** Format: uuid */
            readonly subscription_group_id?: string;
            readonly quantity?: number;
        };
        SubscriptionList: components["schemas"]["Subscription"][];
        Payment: {
            readonly payment_id?: string;
            readonly invoice_id?: string | null;
            readonly billing_account_id?: string;
            /** @enum {string} */
            readonly status?: "succeeded" | "pending" | "failed";
            readonly amount?: number;
            currency?: components["schemas"]["CurrencyCode"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PaymentList: components["schemas"]["Payment"][];
        /** @example USD */
        CurrencyCode: string;
        LabelsMap: {
            [key: string]: string | number | boolean;
        };
        /** @description Grant binding descriptor used by catalog metadata. */
        GrantBinding: {
            program_code?: string;
        } & {
            [key: string]: unknown;
        };
        CatalogGatingMetadata: {
            bundle?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Catalog price metadata. */
        CatalogPriceMetadata: {
            billing_plan_code?: string;
            grants?: components["schemas"]["GrantBinding"][];
            gating?: components["schemas"]["CatalogGatingMetadata"];
        } & {
            [key: string]: unknown;
        };
        BillingEvent: {
            event_id: string;
            /** @enum {string} */
            semantic_kind: "activity" | "outcome";
            /** Format: date-time */
            occurred_at: string;
            event_type: string;
            subject_ref?: string | null;
            payload: {
                [key: string]: unknown;
            };
            labels?: components["schemas"]["LabelsMap"];
            request_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        BillingEventBatchItemResult: {
            index?: number;
            event_id?: string | null;
            /** @enum {string} */
            status?: "accepted" | "duplicate" | "invalid" | "failed";
            error?: components["schemas"]["Error"];
        };
        BillingEventBatchResponse: {
            results?: components["schemas"]["BillingEventBatchItemResult"][];
            accepted_count?: number;
            failed_count?: number;
        };
        RecordBillingEventBatchRequest: {
            events: components["schemas"]["BillingEventIngestRequest"][];
        };
        WalletBalanceResponse: {
            billing_account_id: string;
            billing_user_id: string;
            /**
             * @example xusd
             * @enum {string}
             */
            unit: "xusd";
            /** @description Minor units integer string */
            balance: string;
        };
        WalletConsumeRequest: {
            /** @description Minor units integer string; server applies unit scale */
            amount: string;
            /**
             * @example xusd
             * @enum {string}
             */
            unit: "xusd";
            subject?: string | null;
            /** @description Optional application reference id */
            source_ref?: string | null;
        };
        WalletConsumeResponse: {
            billing_account_id: string;
            billing_user_id: string;
            /** @enum {string} */
            unit: "xusd";
            /** @description Minor units integer string */
            balance: string;
            /** @description True if idempotent replay of a prior success */
            replay?: boolean;
        };
        WalletAdjustmentRequest: {
            /** @description Signed minor units integer string; positive adds, negative subtracts */
            delta: string;
            /**
             * @example xusd
             * @enum {string}
             */
            unit: "xusd";
            /**
             * @description Semantic type of this change
             * @default adjustment
             * @enum {string}
             */
            kind: "grant" | "debit" | "adjustment";
            origin?: {
                /**
                 * @description Where this change originates
                 * @enum {string}
                 */
                kind: "subscription" | "purchase" | "promotion" | "refund" | "reversal" | "ops" | "system" | "migration" | "other";
                /** @description External reference id (invoice/subscription/payment/etc.) */
                ref?: string | null;
                labels?: {
                    [key: string]: string;
                };
            };
            /** @description Short machine-friendly reason code */
            reason_code?: string | null;
            /** @description Human note */
            note?: string | null;
            /** @description Optional client-supplied id for auditing */
            request_id?: string | null;
        };
        CatalogProductListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["CatalogProductList"];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CatalogPriceListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["CatalogPriceList"];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CreateCheckoutSessionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["CreateCheckoutSessionResponse"];
        };
        CreatePortalSessionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["CreatePortalSessionResponse"];
        };
        PlatformTokenIssueRequest: {
            /**
             * @description Caller-defined payor principal identifier (org id, team id, workspace id, customer id, etc.) that maps to the billing account. If you need multiple namespaces, prefix the id yourself (e.g.'org:123').
             *
             * @example org_123
             */
            principal_id: string;
            /**
             * @description Caller-defined runtime user identifier inside the billing account. This becomes the token subject (`sub`) and maps to an internal billing_user_id.
             * @example user_b3f19
             */
            user_id: string;
            /**
             * @description Allowed scopes for the issued platform access token. If omitted, the server will default to a conservative set (e.g. ['checkout', 'portal']) and may ignore unknown values.
             *
             * @example [
             *       "checkout",
             *       "portal"
             *     ]
             */
            scopes?: string[];
            /**
             * Format: int32
             * @description Desired lifetime of the issued token in seconds. The server may cap this to a configured maximum (e.g. 3600 seconds).
             * @default 900
             */
            session_ttl_sec: number;
            /**
             * @description Optional traits for the principal (e.g. email, display name) used for reconciliation and portal display. Not used for authorization.
             * @example {
             *       "email": "user@example.com",
             *       "name": "Jane Doe"
             *     }
             */
            traits?: {
                [key: string]: unknown;
            };
            /** @description Optional opaque value that may be embedded into the issued token for caller-side correlation. */
            nonce?: string;
        };
        PlatformTokenIssueResponse: {
            /** @description Short-lived platform access token. */
            access_token: string;
            /**
             * @description Token type, always "Bearer".
             * @enum {string}
             */
            token_type: "Bearer";
            /**
             * Format: int32
             * @description Lifetime of the token in seconds.
             * @example 900
             */
            expires_in: number;
            /**
             * Format: date-time
             * @description Absolute expiry timestamp in UTC (ISO-8601). Redundant with `expires_in` but convenient for clients.
             * @example 2025-11-17T12:34:56Z
             */
            expires_at?: string;
            billing_account_id: string;
            billing_user_id: string;
        };
        PlatformTokenIssueEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["PlatformTokenIssueResponse"];
        };
        InvoiceListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["InvoiceList"];
            meta?: components["schemas"]["PaginationMeta"];
        };
        InvoiceEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["InvoiceDetail"];
        };
        SubscriptionListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["SubscriptionList"];
            meta?: components["schemas"]["PaginationMeta"];
        };
        SubscriptionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Subscription"];
        };
        PaymentListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["PaymentList"];
            meta?: components["schemas"]["PaginationMeta"];
        };
        PaymentEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Payment"];
        };
        BillingEventBatchResponseEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["BillingEventBatchResponse"];
        };
        WalletBalanceEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["WalletBalanceResponse"];
        };
        WalletConsumeEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["WalletConsumeResponse"];
        };
        PaginationMeta: {
            next_cursor?: string | null;
            /** @default false */
            has_more: boolean;
            limit?: number;
        };
        BillingEventIngestRequest: {
            /**
             * @description Event semantic kind (routing/processing classification).
             * @enum {string}
             */
            semantic_kind: "activity" | "outcome";
            /** @description Event type identifier (e.g., outcome.job_succeeded). */
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description Optional subject reference (job id, request id, etc.) */
            subject_ref?: string | null;
            payload?: {
                [key: string]: unknown;
            };
            labels?: components["schemas"]["LabelsMap"];
        };
        BillingEventEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["BillingEvent"];
        };
        FeatureFamilyRef: {
            feature_family_code: string;
            name: string;
            description?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
        };
        ProductFeatureFamilies: components["schemas"]["FeatureFamilyRef"][];
        CatalogPriceFeatureFamilies: components["schemas"]["FeatureFamilyRef"][];
        SubscriptionState: {
            /** Format: uuid */
            subscription_group_id?: string;
            group_key?: string;
            is_stackable?: boolean;
            has_active_subscription?: boolean;
            eligible_for_checkout?: boolean;
            /** @enum {string} */
            action?: "checkout" | "manage_in_portal" | "add_seats";
            subscription_id?: string;
        };
        Budget: {
            budget_id: string;
            /** Format: uuid */
            billing_account_id?: string;
            name?: string;
            /** @enum {string} */
            status: "active" | "closed" | "expired" | "canceled";
            /** @enum {unknown} */
            scope_kind?: "global" | "feature" | "feature_set" | null;
            scope_payload?: Record<string, never> | null;
            /**
             * Format: int64
             * @description null or empty means unlimited.
             */
            limit_xusd?: string;
            /** Format: int64 */
            consumed_xusd: string;
            /** Format: date-time */
            window_start?: string | null;
            /** Format: date-time */
            window_end?: string | null;
            /** @default {} */
            metadata: Record<string, never>;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description Computed: limit_xusd - consumed_xusd.
             */
            readonly remaining_xusd?: string;
        };
        BudgetCreateRequest: {
            name?: string;
            /** @enum {string} */
            scope_kind?: "global" | "feature" | "feature_set";
            scope_payload?: Record<string, never>;
            /**
             * Format: int64
             * @description XUSD integer-string minor units (1 xusd = 1e-6 USD). Developers and Agents MUST convert user-facing prices before calling this API.
             */
            limit_xusd?: string;
            /** Format: date-time */
            window_start?: string | null;
            /** Format: date-time */
            window_end?: string | null;
            metadata?: Record<string, never>;
        };
        /** @description Optional request body for closing a budget. */
        CloseBudgetBody: {
            /** @description Optional reason or note for closing this budget. */
            reason?: string;
            /** @description Optional metadata for the close operation. */
            metadata?: {
                [key: string]: unknown;
            };
        };
        BudgetOpResponse: {
            budget_id: string;
            /** Format: int64 */
            consumed_xusd: string;
            /** Format: int64 */
            remaining_xusd?: string;
        };
        BudgetEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["Budget"];
        };
        BudgetList: {
            items?: components["schemas"]["Budget"][];
            next_cursor?: string;
        };
        BudgetListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["BudgetList"];
        };
        BudgetOpEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["BudgetOpResponse"];
        };
        /** @description Multi-currency amounts returned as MINOR unit integer strings. Scales follow `currencies` table: XUSD scale=1 (1=1µUSD), USD scale=2 (cents). */
        CurrencyAmounts: {
            /** @description XUSD (micro-USD) minor units as integer string (scale=1). */
            xusd: string;
            /** @description USD cents as integer string (scale=2). */
            usd?: string;
        };
        /** @description Conversion snapshot used to compute USD valuations from XUSD. All ratios are decimal strings; server-defined and realm-scoped. */
        ConversionSnapshot: {
            /** Format: date-time */
            as_of: string;
            /** @description Decimal string. Example: "0.000001" means 1 XUSD = 1e-6 USD. */
            usd_per_xusd: string;
        };
        /** @description Summarized ledger_grants row for balance composition. Windows and remaining are computed-as-of the request time. */
        LedgerGrantView: {
            grant_id: string;
            /** @description Issuance program code (if any). */
            grant_program_code?: string;
            /** @description Human-friendly title (server-provided). */
            name?: string;
            /** @description Source of issuance (subscription|bonus|topup|adjustment|other). */
            origin?: string;
            on_ledger?: boolean;
            /** @description Consumption priority; lower means earlier consumption. */
            priority?: number;
            /** @enum {string} */
            status: "active" | "expired" | "pending_close" | "canceled";
            /** Format: date-time */
            window_start?: string;
            /**
             * Format: date-time
             * @description Grant usage window end (aka expiration).
             */
            window_end?: string;
            issued?: components["schemas"]["CurrencyAmounts"];
            /** @description Remaining amount (may be negative if over-consumed). */
            remaining: components["schemas"]["CurrencyAmounts"];
            /** @description Consumed amount in XUSD minor units (integer string). */
            consumed_xusd?: string;
            labels?: {
                [key: string]: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Optional server-provided condensed summary for UI. */
            display_hint?: string;
        };
        /** @description Runtime user balance with grant composition and multi-currency valuations. */
        WalletBalanceWithBreakdownResponse: {
            billing_account_id: string;
            billing_user_id: string;
            balances: components["schemas"]["CurrencyAmounts"];
            /** @description Net unsettled amounts (may be negative). This includes non-ledger grants (including fallback/overage) and is NOT capped at 0. Use `balances` for spendable amount. */
            outstanding_balances: components["schemas"]["CurrencyAmounts"];
            conversion: components["schemas"]["ConversionSnapshot"];
            grants?: components["schemas"]["LedgerGrantView"][];
        };
        WalletBalanceWithBreakdownEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["WalletBalanceWithBreakdownResponse"];
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Forbidden (realm/account mismatch, billing account not derived from your session/principal, or insufficient role) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict (idempotency body mismatch or duplicate adjustment) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unprocessable Entity (validation, visibility, or binding/meter unresolved) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Provider unavailable / transient failure */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limited */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Realm identifier for the project. Send it as X-Realm-Id. */
        RealmIDHeader: string;
        /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
        RealmAdminHeader: "true";
        /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
        IdempotencyKeyRequired: string;
        Limit: number;
        Cursor: string;
        /** @description Optional idempotency key. For `/events`, the primary idempotency key is the server-side `request_hash`. */
        IdempotencyKeyOptional: string;
        /** @description Optional request correlation ID. The server may echo or override it. */
        XRequestId: string;
        /** @description Budget identifier */
        BudgetId: string;
        /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
        PrincipalIdHeaderRequired: string;
        /** @description External runtime user identifier scoped by the billing account for runtime calls. */
        UserIdHeaderRequired: string;
        /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
        ContentDigestHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCatalogProducts: {
        parameters: {
            query?: {
                /** @description Optional filter by product kind. Defaults to all. */
                kind?: "subscription" | "credit" | "all";
                currency?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Optional expansions. Use to inline related data: feature_families, prices. Supports subscription_state. */
                expand?: ("feature_families" | "prices" | "subscription_state")[];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogProductListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listCatalogPrices: {
        parameters: {
            query: {
                /** @description Catalog product id (cp_ or numeric) Pass one or more ids; repeat the parameter (?product_id=1&product_id=2) or use product_id[]=... syntax. */
                product_id: string[];
                currency?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Filter by recurring interval for subscription prices. */
                recurring_interval?: "month" | "year";
                /** @description Filter by recurring count (e.g., 1 for monthly, 12 for yearly if interval=month). */
                recurring_count?: number;
                /** @description Optional expansions. Use to inline related data: feature_families. Supports subscription_state. */
                expand?: ("feature_families" | "subscription_state")[];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": [
                     *         {
                     *           "catalog_price_id": "price_1",
                     *           "catalog_product_id": "prod_1",
                     *           "provider_price_id": "price_abc123",
                     *           "currency": "USD",
                     *           "unit_amount": 1200,
                     *           "recurring_interval": "month",
                     *           "recurring_count": 1
                     *         }
                     *       ],
                     *       "meta": {
                     *         "next_cursor": "cursor_2",
                     *         "has_more": false,
                     *         "limit": 50
                     *       }
                     *     } */
                    "application/json": components["schemas"]["CatalogPriceListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Checkout URL for redirection */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": {
                     *         "checkout_url": "https://checkout.stripe.com/c/pay_abc"
                     *       }
                     *     } */
                    "application/json": components["schemas"]["CreateCheckoutSessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createPortalSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortalSessionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Portal URL for redirection */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": {
                     *         "portal_url": "https://billing.example.com/portal/session_abc"
                     *       }
                     *     } */
                    "application/json": components["schemas"]["CreatePortalSessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listInvoices: {
        parameters: {
            query: {
                billing_account_id: string;
                /** @description Optional internal subscription id filter. */
                subscription_id?: string;
                status?: "draft" | "open" | "paid" | "uncollectible" | "void";
                /** @description Optional search across invoice id/number/provider invoice id. */
                q?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": [
                     *         {
                     *           "invoice_id": "inv_1",
                     *           "billing_account_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *           "status": "paid",
                     *           "currency": "USD",
                     *           "hosted_invoice_url": "https://billing.example.com/invoices/inv_1",
                     *           "created_at": "2025-09-16T09:31:46Z"
                     *         }
                     *       ],
                     *       "meta": {
                     *         "next_cursor": "cursor_2",
                     *         "has_more": false,
                     *         "limit": 50
                     *       }
                     *     } */
                    "application/json": components["schemas"]["InvoiceListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getInvoice: {
        parameters: {
            query: {
                billing_account_id: string;
                /** @description Optional expansions for invoice line items. */
                expand?: "line_items.catalog_price"[];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listSubscriptions: {
        parameters: {
            query: {
                billing_account_id: string;
                status?: "trialing" | "active" | "past_due" | "canceled" | "unpaid";
                /** @description Optional search across subscription ids. */
                q?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                /** @description Optional expansions for subscription items. */
                expand?: "items.catalog_price"[];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": [
                     *         {
                     *           "subscription_id": "sub_1",
                     *           "billing_account_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *           "status": "active",
                     *           "current_period_start": "2025-09-16T09:31:46Z",
                     *           "current_period_end": "2025-09-16T09:31:46Z",
                     *           "items": [
                     *             {
                     *               "subscription_item_id": "si_123"
                     *             }
                     *           ]
                     *         }
                     *       ],
                     *       "meta": {
                     *         "next_cursor": "cursor_2",
                     *         "has_more": false,
                     *         "limit": 50
                     *       }
                     *     } */
                    "application/json": components["schemas"]["SubscriptionListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSubscription: {
        parameters: {
            query: {
                billing_account_id: string;
                /** @description Optional expansions for subscription items. */
                expand?: "items.catalog_price"[];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listPayments: {
        parameters: {
            query: {
                billing_account_id: string;
                /** @description Optional internal invoice id filter. */
                invoice_id?: string;
                status?: "succeeded" | "pending" | "failed";
                /** @description Optional search across payment ids. */
                q?: string;
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": [
                     *         {
                     *           "payment_id": "pay_1",
                     *           "invoice_id": "inv_1",
                     *           "billing_account_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *           "status": "succeeded",
                     *           "amount": 1200,
                     *           "currency": "USD",
                     *           "created_at": "2025-09-16T09:31:46Z"
                     *         }
                     *       ],
                     *       "meta": {
                     *         "next_cursor": "cursor_2",
                     *         "has_more": false,
                     *         "limit": 50
                     *       }
                     *     } */
                    "application/json": components["schemas"]["PaymentListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPayment: {
        parameters: {
            query: {
                billing_account_id: string;
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    recordBillingEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional idempotency key. For `/events`, the primary idempotency key is the server-side `request_hash`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyOptional"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingEventIngestRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingEventEnvelope"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingEventEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    recordBillingEventBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional idempotency key. For `/events`, the primary idempotency key is the server-side `request_hash`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKeyOptional"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordBillingEventBatchRequest"];
            };
        };
        responses: {
            /** @description Multi-Status (per-item results) */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingEventBatchResponseEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getWalletBalance: {
        parameters: {
            query?: {
                /** @description When true, materialize any lazy grant bindings before computing the balance (idempotent; may add latency). */
                refresh_grants?: boolean;
            };
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": {
                     *         "billing_account_id": "49751fb8-7f44-47d5-8afa-7a0717f32e2c",
                     *         "billing_user_id": "8f2b0174-7b92-4d6d-9bb8-9f97e7105f35",
                     *         "balances": {
                     *           "xusd": "25000000",
                     *           "usd": "2500"
                     *         },
                     *         "outstanding_balances": {
                     *           "xusd": "25000000",
                     *           "usd": "2500"
                     *         },
                     *         "conversion": {
                     *           "as_of": "2025-11-03T12:00:00Z",
                     *           "usd_per_xusd": "0.000001"
                     *         },
                     *         "grants": [
                     *           {
                     *             "grant_id": "1001",
                     *             "grant_program_code": "daily_bonus_xusd",
                     *             "name": "Daily Bonus",
                     *             "origin": "bonus",
                     *             "on_ledger": false,
                     *             "priority": 100,
                     *             "status": "active",
                     *             "window_start": "2025-11-03T00:00:00Z",
                     *             "window_end": "2025-11-04T00:00:00Z",
                     *             "issued": {
                     *               "xusd": "100000",
                     *               "usd": "100"
                     *             },
                     *             "remaining": {
                     *               "xusd": "100000",
                     *               "usd": "100"
                     *             },
                     *             "consumed_xusd": "0",
                     *             "display_hint": "Daily bonus: 10 CREDITS"
                     *           },
                     *           {
                     *             "grant_id": "2001",
                     *             "grant_program_code": "pro_monthly_xusd",
                     *             "name": "Pro Monthly",
                     *             "origin": "subscription",
                     *             "on_ledger": true,
                     *             "priority": 20,
                     *             "status": "active",
                     *             "window_start": "2025-10-08T00:00:00Z",
                     *             "window_end": "2025-12-08T00:00:00Z",
                     *             "issued": {
                     *               "xusd": "200000000",
                     *               "usd": "200000"
                     *             },
                     *             "remaining": {
                     *               "xusd": "150000000",
                     *               "usd": "150000"
                     *             },
                     *             "consumed_xusd": "50000000",
                     *             "display_hint": "Monthly subscription: 150 CREDITS remaining; expires on the 8th of next month"
                     *           }
                     *         ]
                     *       }
                     *     } */
                    "application/json": components["schemas"]["WalletBalanceWithBreakdownEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    walletConsume: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletConsumeRequest"];
            };
        };
        responses: {
            /** @description Consumed (or idempotent replay of a prior success) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "ok": true,
                     *       "code": "OK",
                     *       "data": {
                     *         "billing_account_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *         "billing_user_id": "8f2b0174-7b92-4d6d-9bb8-9f97e7105f35",
                     *         "unit": "xusd",
                     *         "balance": "97050",
                     *         "replay": false
                     *       }
                     *     } */
                    "application/json": components["schemas"]["WalletConsumeEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Insufficient balance (hard cap) */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    walletAdjustment: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletAdjustmentRequest"];
            };
        };
        responses: {
            /** @description Adjusted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletBalanceEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listBudgets: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                status?: ("active" | "closed" | "expired" | "canceled")[];
                scope_kind?: "global" | "feature" | "feature_set";
                feature?: string;
                name?: string;
                window_start_ge?: string;
                window_start_le?: string;
                window_end_ge?: string;
                window_end_le?: string;
                created_at_ge?: string;
                created_at_le?: string;
            };
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createBudget: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetCreateRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetEnvelope"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getBudget: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path: {
                /** @description Budget identifier */
                budget_id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    closeBudget: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path: {
                /** @description Budget identifier */
                budget_id: components["parameters"]["BudgetId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CloseBudgetBody"];
            };
        };
        responses: {
            /** @description Closed budget and returned updated consumption/remaining amounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOpEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    issuePlatformToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for all write operations. Repeating the same route + key + body replays the original response for about 24 hours; conflicting bodies return 409. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformTokenIssueRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformTokenIssueEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
