/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/gate/authorize": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize and check budget */
        post: operations["authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/commits": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit with authoritative pricing snapshot
         * @description Pricing behavior:'floating' uses the current price at commit time.
         */
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/ingest": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest usage without authorize (direct priced commit)
         * @description Directly writes authoritative priced commit facts (billing_ratings + billing_rated_records) without /gate/authorize. Requires Idempotency-Key. Does not enforce quota/rate/balance; intended for service-to-service usage accounting.
         */
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/commits/batch": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch commit with authoritative pricing snapshot per item
         * @description Top-level idempotency via header; per-item idempotency via `items[].idempotency_key`. The server may merge items by pricing fingerprint before rounding, to minimize error and write amplification. Pricing behavior:'floating' uses the current price at commit time.
         */
        post: operations["commitBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/cancel": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a lease */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/limits": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List feature limits and allowed meters
         * @description Use expand[]=quotas and/or expand[]=rates to include corresponding windows.
         */
        get: operations["listFeatureLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gate/meters": {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List accessible meters and their limits
         * @description Optionally include advisory pricing and coverage via expand[]. Final pricing is decided by authorize/commit.
         */
        get: operations["listMeterLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query usage/revenue/cost report (aggregated; requires realm admin privileges)
         * @description Aggregated usage, revenue, and cost report over billing_ratings and billing_rated_records. Requires realm admin privileges; not intended for end-user billing dashboards.
         */
        post: operations["gateOpsQueryUsageReports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query settlement/funding report (aggregated; requires realm admin privileges)
         * @description Aggregated settlement and funding report over billing_rating_allocations. Requires realm admin privileges; not intended for end-user billing dashboards.
         */
        post: operations["gateOpsQuerySettlementReports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/usage/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query usage report scoped to the authenticated billing user (self-service)
         * @description Same schema as /reports/usage, but authenticated end users may only query their own resolved billing user. The server enforces billing_user_id from the token/request context and keeps billing_account_id as the parent payor scope.
         */
        post: operations["gateUsageReportsSelf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/settlements/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query settlement report scoped to the authenticated billing user (self-service)
         * @description Same schema as /reports/settlements, but authenticated end users may only query their own resolved billing user. The server enforces billing_user_id from the token/request context and keeps billing_account_id as the parent payor scope.
         */
        post: operations["gateSettlementReportsSelf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnvelopeBase: {
            /** @example true */
            ok?: boolean;
            code?: string;
            message?: string;
            trace_id?: string;
            /** @description Machine-readable status signals (OK or error). */
            hints?: components["schemas"]["Hint"][];
        };
        ErrorObject: {
            /**
             * @description Known values include: insufficient_budget, invalid_request, conflict, invalid_lease, feature_mismatch, meter_not_allowed_for_feature.
             * @example insufficient_budget
             */
            type?: string;
            details?: string;
            /** @description Number of seconds to wait before retrying (optional) */
            retry_after?: number;
        };
        AuthorizeRequest: {
            /** @description Optional feature_family to bind or auto-create. If provided and not found in this realm, the server may auto-register it. If omitted, the server uses the per-realm fallback feature_family for feature auto-registration.
             *      */
            feature_family_code?: string;
            /** @description Optional; for estimation and hints only, not enforced. */
            estimated_quantity_minor?: string;
            /** @description Optional budget to check against */
            budget_id?: string;
            feature_code: string;
            labels?: {
                [key: string]: string;
            };
        };
        AuthorizeResponse: {
            lease_token: string;
            lease_id?: string;
            budget_id?: string;
            feature_code: string;
            feature_family_code: string;
            /** Format: date-time */
            window_start: string;
            /** Format: date-time */
            window_end: string;
        };
        AuthorizeEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["AuthorizeResponse"];
        };
        CommitRequest: components["schemas"]["SingleCommit"];
        /** @description Server-computed authoritative pricing snapshot at commit time (xusd-only). */
        PricingSnapshot: {
            /** Format: date-time */
            computed_at: string;
            /** @description Meter unit (e.g., tokens, request) */
            unit: string;
            /** @description Stable hash of priced inputs Includes price/quantity/rounding/effective_at/provenance; any change yields a new value. */
            fingerprint: string;
            /** @description Price per block in XUSD (integer string). A block contains. `unit_quantity_minor` meter minor units (default 1). */
            unit_price_xusd: string;
            /** @description Base price per block in XUSD before dynamic adjustments (integer string). */
            unit_price_base_xusd?: string;
            /** @description Dynamic adjustment per block in XUSD (integer string; may be negative). */
            unit_price_dynamic_xusd?: string;
            tier_applied?: {
                [key: string]: unknown;
            };
            /** @description Size of one pricing block in meter minor units (≥1). When >1, block pricing is used. */
            unit_quantity_minor?: string;
            /**
             * @description Rounding strategy applied when computing xusd from blocks.
             * @enum {string}
             */
            rounding?: "floor" | "nearest" | "ceil";
            /** @description Source and inputs used to price this commit. */
            provenance?: components["schemas"]["ProvenanceLive"] | components["schemas"]["ProvenanceAggregate"];
            /**
             * Format: date-time
             * @description Effective time of the price row used for this snapshot. Price changes produce a new fingerprint.
             */
            effective_at?: string;
        };
        ProvenanceLive: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "missing" | "live";
            inputs: {
                feature_code: string;
                meter_code: string;
            };
        };
        ProvenanceAggregate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "aggregate";
            inputs: {
                feature_code: string;
                items: string[];
            };
        };
        CommitResponse: {
            commit_id?: string;
            budget_id?: string;
            budget_consumed_delta_xusd?: string;
            budget_remaining_xusd?: string;
            /** @description Authoritative amount debited for this commit request in XUSD. (integer string). */
            amount_xusd: string;
            lines?: {
                line_id: string;
                meter_code: string;
                /** Format: int64 */
                quantity_minor: string;
                /** Format: int64 */
                unit_price_xusd?: string;
                /** Format: int64 */
                amount_xusd: string;
                pricing_snapshot?: components["schemas"]["PricingSnapshot"];
                pricing_fingerprint?: string;
                /** Format: int64 */
                cost_xusd?: string;
                /**
                 * Format: int64
                 * @description Cost per block in XUSD (integer string).
                 */
                unit_cost_xusd?: string;
                /**
                 * Format: int64
                 * @description Block size for cost in meter minor units (≥1 means block pricing).
                 */
                cost_unit_quantity_minor?: string;
                /** @enum {string} */
                cost_rounding?: "floor" | "nearest" | "ceil";
                cost_snapshot?: components["schemas"]["PricingSnapshot"];
                cost_fingerprint?: string;
            }[];
            /**
             * Format: int64
             * @description Authoritative total cost for this commit request in XUSD (integer. string).
             */
            cost_xusd?: string;
        };
        CommitEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["CommitResponse"];
        };
        CancelRequest: {
            lease_token: string;
        };
        CancelResponse: {
            /** @example true */
            cancelled: boolean;
            /** @description Unused portion released */
            released_cap?: string;
            trace_id?: string;
        };
        CancelEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["CancelResponse"];
        };
        QuotaWindow: {
            /**
             * @description Counter subject scope for this quota window.
             * @enum {string}
             */
            subject_scope?: "user" | "account";
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            limit_minor?: string;
            used_minor?: string;
        };
        RateWindow: {
            /**
             * @description Counter subject scope for this rate window.
             * @enum {string}
             */
            subject_scope?: "user" | "account";
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            /** @description Max requests in window */
            limit_minor?: string;
            /** @description Requests used in window */
            used_minor?: string;
        };
        FeatureLimit: {
            feature_code?: string;
            feature_family_code?: string;
            unit?: string;
            quotas?: components["schemas"]["QuotaWindow"][];
            rates?: components["schemas"]["RateWindow"][];
            /** @description Allowed meters for this feature (whitelist used by commit validation) */
            meters?: string[];
        };
        FeatureLimitListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["FeatureLimit"][];
        };
        BatchCommitItem: components["schemas"]["SingleCommit"] & {
            /** @description Per-item idempotency key within the batch. The server deduplicates per lease scope (e.g., unique on (lease_id, idempotency_key)). Top-level Idempotency-Key header still applies to the whole batch. */
            idempotency_key: string;
        };
        BatchCommitRequest: {
            items: components["schemas"]["BatchCommitItem"][];
            /**
             * @description Optional advice: merge by pricing fingerprint within the batch before rounding to reduce write amplification and rounding error.
             * @default by_pricing_fingerprint
             * @enum {string}
             */
            merge_advice: "none" | "by_pricing_fingerprint";
        };
        BatchCommitItemResult: {
            index?: number;
            /** @enum {string} */
            status?: "committed" | "duplicate" | "invalid" | "failed";
            commit?: components["schemas"]["CommitResponse"];
            error?: components["schemas"]["ErrorObject"];
        };
        BatchCommitResponse: {
            items?: components["schemas"]["BatchCommitItemResult"][];
            committed_count?: number;
            failed_count?: number;
        };
        BatchCommitEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["BatchCommitResponse"];
        };
        MeterCommit: {
            meter_code: string;
            /** Format: int64 */
            quantity_minor: string;
            unit?: string;
            client_pricing_etag?: string;
            /**
             * Format: int64
             * @description XUSD integer-string minor units (1 xusd = 1e-6 USD). Developers and Agents MUST convert user-facing prices before calling this API.
             */
            client_unit_price_xusd?: string;
        };
        IngestCommit: {
            feature_code: string;
            /**
             * Format: date-time
             * @description Business occurrence time for this usage fact. When provided, the server uses it as the rating attribution time instead of the ingest write time.
             */
            occurred_at?: string;
            /**
             * Format: int64
             * @description Feature-level quantity dimension for analytics/limits (may differ from sum(meters[].quantity_minor)).
             */
            quantity_minor?: string;
            /** @description Optional budget identifier for attribution/analytics. Not enforced by /gate/ingest. */
            budget_id?: string;
            /** @description Optional labels for attribution/analytics (string map). */
            labels?: {
                [key: string]: string;
            };
            meters?: components["schemas"]["MeterCommit"][];
            metadata?: {
                [key: string]: unknown;
            };
        } & ({
            quantity_minor: unknown;
        } | {
            meters: unknown;
        });
        /** @description Common commit item payload (used by single and batch commits). Uses the lease_token issued by authorize; you do not need the lease id. */
        SingleCommit: {
            /** @description Opaque feature_family token issued by /gate/authorize. The server resolves it to the underlying lease. */
            lease_token: string;
            /**
             * Format: int64
             * @description Feature-level usage quantity (gate dimension). This value is used for authorize/lease/quota/rate accounting at the feature level and may differ from any meter-level breakdown in `meters[]`. Do not assume `quantity_minor == sum(meters[].quantity_minor)`.
             */
            quantity_minor: string;
            /** @description Optional labels for attribution/analytics (string map). */
            labels?: {
                [key: string]: string;
            };
            /** @description Must match the lease */
            feature_code: string;
            /**
             * Format: date-time
             * @description Effective only when pricing_mode=floating
             */
            as_of?: string;
            /** @description Meter-level pricing lines for pricing only Server validates `meters[].meter_code` against the feature_meters whitelist for `feature_code`. Default policy: deny (422 UnprocessableEntity) with error.type='meter_not_allowed_for_feature'. */
            meters?: components["schemas"]["MeterCommit"][];
        };
        MeterLimit: {
            meter_code?: string;
            unit?: string;
            features?: string[];
            feature_family_codes?: string[];
            quotas?: components["schemas"]["QuotaWindow"][];
            rates?: components["schemas"]["RateWindow"][];
            /** @description Advisory price row; returned when expand[]=pricing or implied by coverage */
            pricing?: components["schemas"]["MeterPriceView"];
            /** @description Advisory; returned when expand[]=coverage */
            coverage?: components["schemas"]["MeterCoverage"];
        };
        MeterLimitListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data?: components["schemas"]["MeterLimit"][];
        };
        MeterPriceView: {
            /** @description Price per block in XUSD. */
            unit_price_xusd?: string;
            /** @description Block size in meter minor units (≥1 means block pricing) */
            unit_quantity_minor?: string;
            /** @enum {string} */
            rounding?: "floor" | "nearest" | "ceil";
            /** Format: date-time */
            effective_at?: string;
            fingerprint?: string;
            /** @description Meter unit label (e.g., token, request) */
            unit?: string;
            /** @description Cost per block in XUSD. */
            unit_cost_xusd?: string;
            /** @description Cost block size in meter minor units (≥1 means block pricing) */
            cost_unit_quantity_minor?: string;
            /** @enum {string} */
            cost_rounding?: "floor" | "nearest" | "ceil";
        };
        MeterCoverage: {
            /** @enum {string} */
            basis: "xusd" | "budget";
            /** @description Available balance (xusd) used as basis. */
            balance_xusd: string;
            /** @description Conservative estimate: floor(balance / price_per_block) * unit_quantity_minor */
            max_quantity_minor_estimated: string;
            /** @description Present when profile=optimistic|both */
            optimistic_quantity_minor?: string;
            /** @constant */
            advisory: true;
            /** Format: date-time */
            as_of: string;
            notes?: string;
            budget_id?: string;
        };
        Hint: {
            /** @enum {string} */
            type: "rate.limit" | "funding.xusd_shortfall" | "budget.shortfall" | "quota.remaining" | "budget.low_headroom" | "pricing.changed" | "lease.expired" | "lease.closed_at_commit" | "policy.window_not_found" | "feature.meter_not_allowed" | "pricing.not_configured" | "pricing.contract_term_invalid" | "pricing.meter_price_missing";
        } & {
            [key: string]: unknown;
        };
        PaginationMeta: {
            next_cursor?: string | null;
            /** @default false */
            has_more: boolean;
            limit?: number;
        };
        GateOpsUsageReportMeta: components["schemas"]["PaginationMeta"] & {
            cursor_hint?: {
                time: components["schemas"]["GateReportTimeRange"];
                group_by: components["schemas"]["GateOpsUsageReportDimensionKey"][];
                metrics: components["schemas"]["GateOpsUsageReportMetricKey"][];
                /** @enum {string} */
                aggregate?: "series" | "total" | "group_total";
            };
        };
        GateOpsSettlementReportMeta: components["schemas"]["PaginationMeta"] & {
            cursor_hint?: {
                time: components["schemas"]["GateReportTimeRange"];
                group_by: components["schemas"]["GateOpsSettlementReportDimensionKey"][];
                metrics: components["schemas"]["GateOpsSettlementReportMetricKey"][];
            };
        };
        /** @description Time window and aggregation granularity for gate operations reports. */
        GateReportTimeRange: {
            /**
             * Format: date-time
             * @description Inclusive start time in UTC (must end with 'Z').
             */
            from: string;
            /**
             * Format: date-time
             * @description Exclusive end time in UTC (must end with 'Z').
             */
            to: string;
            /** @enum {string} */
            granularity: "day" | "month";
        };
        /** @enum {string} */
        GateOpsUsageReportDimensionKey: "bucket_start" | "billing_account_id" | "billing_user_id" | "feature_code" | "feature_family_code" | "meter_code" | "pricing_fingerprint" | "cost_fingerprint" | "attribution_kind" | "attribution_id";
        /** @enum {string} */
        GateOpsUsageReportMetricKey: "quantity_minor" | "amount_xusd" | "cost_xusd" | "margin_xusd" | "commit_count" | "line_count" | "distinct_billing_account_count" | "distinct_billing_user_count";
        GateOpsUsageReportDimensionFilter: {
            field: components["schemas"]["GateOpsUsageReportDimensionKey"];
            /** @enum {string} */
            op: "eq" | "in";
            value: string | string[];
        };
        GateOpsUsageReportMetricFilter: {
            field: components["schemas"]["GateOpsUsageReportMetricKey"];
            /** @enum {string} */
            op: "gte" | "lte" | "gt" | "lt";
            /** @description Threshold value as integer/decimal string. */
            value: string;
        };
        GateOpsUsageReportQuery: {
            time: components["schemas"]["GateReportTimeRange"];
            /** @description Dimension keys to group by. bucket_start will be auto-added if missing. */
            group_by: components["schemas"]["GateOpsUsageReportDimensionKey"][];
            /**
             * @description Use "total" to return a single aggregated row. When set to "total", group_by must be bucket_start only. Use "group_total" to aggregate across the time range while still grouping by the remaining dimensions; bucket_start becomes a constant anchor.
             * @enum {string}
             */
            aggregate?: "series" | "total" | "group_total";
            /**
             * @description Return comparison data for the previous time window. Only supported when aggregate=total or when group_by includes only bucket_start. Not supported with cursor.
             * @enum {string}
             */
            compare?: "previous";
            /** @description Limit results to the top N dimension values ranked by order_by_metric over the full time range. Supported only when group_by includes bucket_start and exactly one of feature_code/feature_family_code. With aggregate=group_total, top_k also supports attribution_id (requires attribution_kind=plan) and billing_account_id or billing_user_id (time window <= 90 days, top_k <= 50, and metrics limited to amount_xusd/cost_xusd/margin_xusd). Not supported with cursor or compare. */
            top_k?: number;
            /** @description Metric used to rank top_k results. Defaults to the first metric in metrics. */
            order_by_metric?: components["schemas"]["GateOpsUsageReportMetricKey"];
            /**
             * @description Sort order for top_k ranking (default desc).
             * @enum {string}
             */
            order?: "desc" | "asc";
            metrics?: components["schemas"]["GateOpsUsageReportMetricKey"][];
            dim_filters?: components["schemas"]["GateOpsUsageReportDimensionFilter"][];
            metric_filters?: components["schemas"]["GateOpsUsageReportMetricFilter"][];
            limit?: number;
            cursor?: string;
        };
        GateOpsUsageReportRow: {
            /** Format: date-time */
            bucket_start: string;
            billing_account_id?: string;
            billing_user_id?: string;
            feature_code?: string;
            feature_family_code?: string;
            meter_code?: string;
            pricing_fingerprint?: string;
            cost_fingerprint?: string;
            /** @description Attribution category (for example plan, plan_assignment, subscription_item, subscription). */
            attribution_kind?: string;
            /** @description Identifier scoped to attribution_kind (plan_id, assignment_id, subscription_item_id, etc.). */
            attribution_id?: string;
            labels?: {
                [key: string]: string;
            };
            quantity_minor?: string;
            amount_xusd?: string;
            cost_xusd?: string;
            margin_xusd?: string;
            /** Format: int64 */
            commit_count?: number;
            /** Format: int64 */
            line_count?: number;
            /** Format: int64 */
            distinct_billing_account_count?: number;
            /** Format: int64 */
            distinct_billing_user_count?: number;
        };
        GateOpsUsageReportResult: {
            /** @enum {string} */
            granularity: "day" | "month";
            group_by: components["schemas"]["GateOpsUsageReportDimensionKey"][];
            metrics: components["schemas"]["GateOpsUsageReportMetricKey"][];
            rows: components["schemas"]["GateOpsUsageReportRow"][];
            compare_rows?: components["schemas"]["GateOpsUsageReportRow"][];
            compare_time?: components["schemas"]["GateReportTimeRange"];
            totals?: {
                [key: string]: string;
            };
            compare_totals?: {
                [key: string]: string;
            };
            delta?: {
                [key: string]: string;
            };
            delta_pct?: {
                [key: string]: number | null;
            };
        };
        GateOpsUsageReportEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["GateOpsUsageReportResult"];
            meta?: components["schemas"]["GateOpsUsageReportMeta"];
        };
        /** @enum {string} */
        GateOpsSettlementReportDimensionKey: "bucket_start" | "billing_account_id" | "billing_user_id" | "feature_code" | "feature_family_code" | "funding_kind" | "application_status" | "budget_id" | "grant_id" | "grant_program_id" | "pricing_fingerprint" | "settlement_state";
        /** @enum {string} */
        GateOpsSettlementReportMetricKey: "allocated_amount_xusd" | "applied_amount_xusd" | "applied_cost_xusd" | "settlement_count";
        GateOpsSettlementReportDimensionFilter: {
            field: components["schemas"]["GateOpsSettlementReportDimensionKey"];
            /** @enum {string} */
            op: "eq" | "in";
            value: string | string[];
        };
        GateOpsSettlementReportMetricFilter: {
            field: components["schemas"]["GateOpsSettlementReportMetricKey"];
            /** @enum {string} */
            op: "gte" | "lte" | "gt" | "lt";
            value: string;
        };
        GateOpsSettlementReportQuery: {
            time: components["schemas"]["GateReportTimeRange"];
            /** @description Dimension keys to group by. bucket_start will be auto-added if missing.
             *     Supported combinations (after sorting/dedup) are limited to:
             *     ['bucket_start'], ['bucket_start','funding_kind'], ['bucket_start','billing_account_id'], ['bucket_start','billing_user_id'],
             *     ['bucket_start','feature_code'], ['bucket_start','grant_id'], ['bucket_start','grant_program_id'], ['bucket_start','budget_id'],
             *     ['bucket_start','application_status'], ['bucket_start','funding_kind','application_status'], ['bucket_start','feature_code','funding_kind'],
             *     ['bucket_start','grant_program_id','funding_kind']. */
            group_by: components["schemas"]["GateOpsSettlementReportDimensionKey"][];
            metrics?: components["schemas"]["GateOpsSettlementReportMetricKey"][];
            dim_filters?: components["schemas"]["GateOpsSettlementReportDimensionFilter"][];
            metric_filters?: components["schemas"]["GateOpsSettlementReportMetricFilter"][];
            limit?: number;
            cursor?: string;
        };
        GateOpsSettlementReportRow: {
            /** Format: date-time */
            bucket_start: string;
            billing_account_id?: string;
            billing_user_id?: string;
            feature_code?: string;
            feature_family_code?: string;
            funding_kind?: string;
            application_status?: string;
            budget_id?: string | null;
            grant_id?: string | null;
            grant_program_id?: string | null;
            pricing_fingerprint?: string;
            settlement_state?: string;
            labels?: {
                [key: string]: string;
            };
            allocated_amount_xusd?: string;
            applied_amount_xusd?: string;
            applied_cost_xusd?: string;
            /** Format: int64 */
            settlement_count?: number;
        };
        GateOpsSettlementReportResult: {
            /** @enum {string} */
            granularity: "day" | "month";
            group_by: components["schemas"]["GateOpsSettlementReportDimensionKey"][];
            metrics: components["schemas"]["GateOpsSettlementReportMetricKey"][];
            rows: components["schemas"]["GateOpsSettlementReportRow"][];
        };
        GateOpsSettlementReportEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["GateOpsSettlementReportResult"];
            meta?: components["schemas"]["GateOpsSettlementReportMeta"];
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
        /** @description Payment required or insufficient budget */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
        /** @description Unprocessable entity. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
        /** @description Too many requests (rate limited) */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeBase"] & {
                    error?: components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    parameters: {
        /** @description Realm identifier for the project. Send it as X-Realm-Id. */
        RealmIDHeader: string;
        /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
        RealmAdminHeader: "true";
        /** @description Required admin flag for realm-wide report queries. Must be true. */
        RealmAdminHeaderRequired: "true";
        /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
        IdempotencyKeyRequired: string;
        /** @description Optional request correlation ID. The server may echo or override it. */
        XRequestId: string;
        /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
        PrincipalIdHeaderRequired: string;
        /** @description External runtime user identifier scoped by the billing account for runtime calls. */
        UserIdHeaderRequired: string;
        /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
        ContentDigestHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authorize: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizeEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            /** @description Rate limit exceeded; no hints are returned. */
            429: {
                headers: {
                    /** @description Suggested wait time in seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorObject"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SingleCommit"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestCommit"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    commitBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCommitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCommitEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Required for authorize/commit/cancel. Repeating the same endpoint and key replays the first successful response. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
                /** @description Body integrity digest. Format: sha-256=:<BASE64(SHA256(raw_body_bytes))>: */
                "Content-Digest": components["parameters"]["ContentDigestHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listFeatureLimits: {
        parameters: {
            query?: {
                /** @description Filter by feature_code (repeatable) */
                feature_code?: string[];
                /** @description Filter by feature_family_code (repeatable) */
                feature_family_code?: string[];
                /** @description Evaluate windows as of this time (default now) */
                as_of?: string;
                /** @description Select which subviews to embed */
                expand?: ("quotas" | "rates")[];
            };
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureLimitListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMeterLimits: {
        parameters: {
            query?: {
                /** @description Filter by meter code (repeatable) */
                meter_code?: string[];
                /** @description Only meters authorized by these features */
                feature_code?: string[];
                /** @description Only meters authorized by these feature_families */
                feature_family_code?: string[];
                /** @description Evaluate windows as of this time (default now) */
                as_of?: string;
                include_quotas?: boolean;
                include_rates?: boolean;
                /** @description Subviews to embed. 'limits' implies both 'quotas' and 'rates'. 'coverage' implies 'pricing'. */
                expand?: ("limits" | "quotas" | "rates" | "pricing" | "coverage")[];
                /** @description xusd | budget (default xusd) */
                "coverage.basis"?: "xusd" | "budget";
                /** @description When basis=budget, use this budget's available xusd */
                "coverage.budget_id"?: string;
                /** @description Default conservative */
                "coverage.profile"?: "conservative" | "optimistic" | "both";
                /** @description Defaults to as_of or now */
                "coverage.as_of"?: string;
            };
            header: {
                /** @description External payor principal identifier used to resolve the billing account for runtime calls. */
                "X-Principal-Id": components["parameters"]["PrincipalIdHeaderRequired"];
                /** @description External runtime user identifier scoped by the billing account for runtime calls. */
                "X-User-Id": components["parameters"]["UserIdHeaderRequired"];
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterLimitListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    gateOpsQueryUsageReports: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Required admin flag for realm-wide report queries. Must be true. */
                "X-Realm-Admin": components["parameters"]["RealmAdminHeaderRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateOpsUsageReportQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOpsUsageReportEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    gateOpsQuerySettlementReports: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Required admin flag for realm-wide report queries. Must be true. */
                "X-Realm-Admin": components["parameters"]["RealmAdminHeaderRequired"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateOpsSettlementReportQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOpsSettlementReportEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    gateUsageReportsSelf: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateOpsUsageReportQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOpsUsageReportEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    gateSettlementReportsSelf: {
        parameters: {
            query?: never;
            header: {
                /** @description Realm identifier for the project. Send it as X-Realm-Id. */
                "X-Realm-Id": components["parameters"]["RealmIDHeader"];
                /** @description Optional admin flag to enable realm-wide RLS for authorized callers. */
                "X-Realm-Admin"?: components["parameters"]["RealmAdminHeader"];
                /** @description Optional request correlation ID. The server may echo or override it. */
                "X-Request-Id"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateOpsSettlementReportQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOpsSettlementReportEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
